# https://github.com/bcabic/course-material
# bcabic
language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
# make directory for build
  - mkdir dist
  - cd dist
  - ls -la

install:
  - ls -la
  - npm install
  - ls -la
